language: objective-c

xcode_project: NSData+APNSToken.xcodeproj
xcode_scheme: NSData+APNSTokenTests

script:
  - set -o pipefail && xcodebuild test -project "NSData+APNSToken.xcodeproj" -scheme NSData+APNSTokenTests -destination "platform=iOS Simulator,name=iPhone 6s" | xcpretty
  - pod lib lint
